# Generated by Django 4.0.1 on 2022-04-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('n_tarjeta', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('f_vencimiento', models.DateField()),
                ('saldo', models.FloatField()),
                ('limite', models.FloatField()),
                ('es_bloqueada', models.BooleanField()),
                ('es_verificada', models.BooleanField()),
                ('intento', models.IntegerField()),
            ],
            options={
                'ordering': ('-n_tarjeta',),
            },
        ),
    ]
