# Generated by Django 4.0.1 on 2022-04-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_banco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='nip',
            field=models.PositiveSmallIntegerField(default=1111),
            preserve_default=False,
        ),
    ]
